# Generated by Django 4.2.8 on 2024-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topranked',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
