# Generated by Django 4.2.8 on 2024-01-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_topranked_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topranked", name="counter", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="topranked", name="url", field=models.CharField(max_length=200),
        ),
    ]
