# Generated by Django 4.2.8 on 2024-01-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_topranked_counter_alter_topranked_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topranked",
            name="counter",
            field=models.IntegerField(default=1),
        ),
    ]
