# Generated by Django 4.2.8 on 2024-01-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_topranked_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topranked",
            name="counter",
            field=models.IntegerField(default=0),
        ),
    ]
