# Generated by Django 4.2.8 on 2024-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="published_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
