# Generated by Django 4.2.8 on 2024-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_news_content_alter_news_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
