# Generated by Django 4.2.8 on 2024-01-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_news_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
